-- Create the 'users' table if it does not exist
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR,
    password VARCHAR
);

-- Create the 'movies' table if it does not exist
CREATE TABLE IF NOT EXISTS movies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR
);

-- Create the 'users_topic' table if it does not exist
CREATE TABLE IF NOT EXISTS users_topic (
    id BIGINT PRIMARY KEY,
    username VARCHAR,
    password VARCHAR
);

-- Create the 'movies_topic' table if it does not exist
CREATE TABLE IF NOT EXISTS movies_topic (
    id BIGINT PRIMARY KEY,
    title VARCHAR
);

-- Create the 'user_movie_mapping' table if it does not exist
CREATE TABLE IF NOT EXISTS user_movie_mapping (
    user_id BIGINT REFERENCES users(id),
    movie_id BIGINT REFERENCES movies_topic(id),
    PRIMARY KEY (user_id, movie_id)
);
